[features]
seeds = false
skip-lint = false

[programs.localnet]
gift_bridge_solana = "EKAeT88SXnVSFT74MVgYG7tfLKuux271UURqN1FQa5Gf"

[programs.devnet]
gift_bridge_solana = "EKAeT88SXnVSFT74MVgYG7tfLKuux271UURqN1FQa5Gf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "accounts/solana-admin-relayer.json"

[workspace]
members = ["programs/gift_bridge_solana"]

[toolchain]
anchor_version = "0.31.0"

